### ISSUE TITLE
Failed upgrade 'Command "maintenance:mode" is not defined.'

### ISSUE THREAD

**Issue by zamentur** [YunoHost-Apps/nextcloud_ynh#403] opened 2021-05-08 11:27 UTC
I was upgrading a 4.1.7 yunohost server to nextcloud 20.0.8~ynh1
This server has some change so it could link to this, it's possible the config.php was modified.

I experiment an error during this nextcloud upgrade but hopefully it was able to restore automatically.

```
Command "maintenance:mode" is not defined.
Did you mean this?
      maintenance:install
```

After research my config.php was empty so nextcloud is considered as uninstalled. Don’t know why exactly it was empty.

Full log: https://paste.yunohost.org/ukefowuzos.bash

**Comment by alexAubin** [comment] 2024-06-24 12:32
Closing because 3 years old an it's because config.php was empty, no idea why nor how to reproduce

**Closed by alexAubin** 2024-06-24 12:32 UTC
