### ISSUE TITLE
Access forbidden: Nextcloud became inaccessible 

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/nextcloud_ynh#74] opened 2017-11-26 09:17 UTC
Hi
Suddenly the Nextcloud became Inaccessible with the login page saying **access forbidden**. I am on testing branch.

I had to add `cgi.fix_pathinfo=1` to /etc/php5/conf.d/nextcloud.ini to make it work again. 
What could be the cause of this sudden denial of access ?

**Comment by SuperSandro2000** [comment] 2018-04-02 12:01
Still happening....

**Comment by alexAubin** [comment] 2023-01-16 15:16
Closing because this was 5 years ago , a shitload changed since then, can't reproduce

**Closed by alexAubin** 2023-01-16 15:16 UTC
Labels: bug
