### ISSUE TITLE
Nextcloud 30.0.1 & MariaDB >=10.6

### ISSUE THREAD

**Issue by genma** [YunoHost-Apps/nextcloud_ynh#741] opened 2024-10-25 08:54 UTC
In a virtual Machine I do some test for Yunohost, I've tested the manual upgrade of an existing Nextcloud (29.0.x) to latest Nextcloud version, 30.0.1.

In the Administration interface Nextcloud says "MariaDB version "10.5.26-MariaDB-0+deb11u2" detected. MariaDB >=10.6 and <=11.4 is suggested for best performance, stability and functionality with this version of Nextcloud."

Yunohost is still in Debian 11 and the MariaDB version. For the moment, Yunohost can still run the latest Nextcloud version, but in the future, we need to see if the migration to Debian 12 (in testing/progress for Yunohost) won't be mandatory, in order to run future version of Nextcloud (prerequirement will be an actual MariaDB version or higher PHP version).

We'll see, we have to keep an eye on it.

**Comment by ericgaspar** [comment] 2024-10-25 09:37
We are trying to follow Nextcloud requirements for DB and PHP version. and I think version 30.0.x will be pushed to master after YunoHost 12 is released.
(Closing as this not a bug)

**Closed by ericgaspar** 2024-10-25 09:37 UTC
