### ISSUE TITLE
After backup restoration (from 18.0.4 back to 18.0.2), Files-app only displays the left panel and right side is blank

### ISSUE THREAD

**Issue by pepeciseaux** [YunoHost-Apps/nextcloud_ynh#307] opened 2020-06-08 13:29 UTC
I think most of the description is in the title. Plus: according to the [screenshot](http://imgur.com/H91ILqu.png), you can see that files seem to still be there and I can tell that the displayed size is correct.

My others apps (Contacts and Map) seem normal.

Any idea? Let me know if I can give some more useful details.

Note:
You may wonder why I made a restoration, and whether it could have a link with the bug here. The reason is because after upgrade, Map was not anymore displaying contacts which have a `geo` property. For the moment I see no link between the two issues, thus this report. About the Map issue I am investigating and will possibly make a report if relevant.

**Comment by pepeciseaux** [comment] 2020-06-08 16:36
Hum, I just noticed one thing. Since the restoration used an automatic backup (made during initial upgrade from 18.0.2 to -.4), could the blank right side be due to `BACKUP_CORE_ONLY` option being activated (left to default)? Can someone confirm whether it would be a consistent explanation or not?

(I knew I had to deactivate that option… I use Files rarely)

**Comment by alexAubin** [comment] 2024-06-24 12:43
Closing because it's 4 years old and seems related to some weird interaction with backup_core_only, seems pretty difficult to reproduce idk

**Closed by alexAubin** 2024-06-24 12:43 UTC
