### ISSUE TITLE
Impossible to access nextcloud after installation

### ISSUE THREAD

**Issue by gwenderer** [YunoHost-Apps/nextcloud_ynh#110] opened 2018-04-29 13:52 UTC
Hello,
I'm running yunohost on a vps server but I had already the issue I'm going to talk about when I installed yunohost on a raspberry pi 3b.
When I installed the app nextcloud the first time, everything works well but when I try to get into the app I get this message
![screenshot-2018-4-29 nextcloud](https://user-images.githubusercontent.com/28829519/39407347-f60694b0-4bc4-11e8-9ddf-9fe0f74e0786.png)
And after, when I uninstall the app and I install it again, when I get into the app, everything is good.

**Comment by SiM** [comment] 2018-05-27 22:08
It seems to be the same problem I have reported in  #98

**Comment by KibaFox** [comment] 2018-05-28 14:13
Certainly.  I took out sensitive information.

```
{"reqId":"yax02DfmDtkqZNTeAnje","level":3,"time":"2018-05-28T14:06:48+00:00","remoteAddr":"******","user":"user_name","app":"PHP","method":"GET","url":"\/nextcloud\/","message":"opendir(\/home\/yunohost.app\/nextcloud\/data\/user_name\/cache): failed to open dir: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#123","userAgent":"******","version":"13.0.1.1"}
{"reqId":"yax02DfmDtkqZNTeAnje","level":3,"time":"2018-05-28T14:06:48+00:00","remoteAddr":"******","user":"user_name","app":"index","method":"GET","url":"\/nextcloud\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(176): OC\\\\Files\\\\Node\\\\Node->checkPermissions(4)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/util.php(445): OC\\\\Files\\\\Node\\\\Folder->newFile('Nextcloud Manua...')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/util.php(415): OC_Util::copyr('\\\/var\\\/www\\\/nextcl...', Object(OC\\\\Files\\\\Node\\\\Folder))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(503): OC_Util::copySkeleton('user_name', Object(OC\\\\Files\\\\Node\\\\Folder))\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(370): OC\\\\User\\\\Session->prepareUserLogin(true, false)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(564): OC\\\\User\\\\Session->completeLogin(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(335): OC\\\\User\\\\Session->loginWithPassword(*** sensitive parameters replaced ***)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(411): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(525): OC\\\\User\\\\Session->logClientIn(*** sensitive parameters replaced ***)\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1052): OC\\\\User\\\\Session->tryBasicAuthLogin(Object(OC\\\\AppFramework\\\\Http\\\\Request), Object(OC\\\\Security\\\\Bruteforce\\\\Throttler))\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(987): OC::handleLogin(Object(OC\\\\AppFramework\\\\Http\\\\Request))\\n#13 \\\/var\\\/www\\\/nextcloud\\\/index.php(37): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}","userAgent":"******","version":"13.0.1.1"}
{"reqId":"fdzaQ5sjA4ETXVT9TON4","level":3,"time":"2018-05-28T14:06:50+00:00","remoteAddr":"******","user":"user_name","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/js\/core\/merged-template-prepend.js?v=64953ac3-0","message":"opendir(\/home\/yunohost.app\/nextcloud\/data\/user_name\/cache): failed to open dir: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#123","userAgent":"******","version":"13.0.1.1"}
{"reqId":"wp2Ytj8GtO0cZzerOMDn","level":3,"time":"2018-05-28T14:06:50+00:00","remoteAddr":"******","user":"user_name","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/js\/core\/merged-share-backend.js?v=64953ac3-0","message":"opendir(\/home\/yunohost.app\/nextcloud\/data\/user_name\/cache): failed to open dir: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#123","userAgent":"******","version":"13.0.1.1"}
{"reqId":"ddh2ozrlkuLgBYZrQvDt","level":3,"time":"2018-05-28T14:06:51+00:00","remoteAddr":"******","user":"user_name","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/theming\/styles?v=0","message":"opendir(\/home\/yunohost.app\/nextcloud\/data\/user_name\/cache): failed to open dir: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#123","userAgent":"******","version":"13.0.1.1"}
{"reqId":"Y0X029R8h9wyEjQiLdUf","level":3,"time":"2018-05-28T14:06:51+00:00","remoteAddr":"******","user":"user_name","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/theming\/js\/theming?v=0","message":"opendir(\/home\/yunohost.app\/nextcloud\/data\/user_name\/cache): failed to open dir: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#123","userAgent":"******","version":"13.0.1.1"}
{"reqId":"ldmosJafMPU9dsJoTVuP","level":3,"time":"2018-05-28T14:06:51+00:00","remoteAddr":"******","user":"user_name","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/js\/core\/merged-share-backend.js?v=64953ac3-0","message":"opendir(\/home\/yunohost.app\/nextcloud\/data\/user_name\/cache): failed to open dir: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#123","userAgent":"******","version":"13.0.1.1"}
{"reqId":"Q2p7ZZrtJziRK1V5ttao","level":3,"time":"2018-05-28T14:06:52+00:00","remoteAddr":"******","user":"user_name","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/js\/core\/merged-template-prepend.js?v=64953ac3-0","message":"opendir(\/home\/yunohost.app\/nextcloud\/data\/user_name\/cache): failed to open dir: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#123","userAgent":"******","version":"13.0.1.1"}
{"reqId":"LjdYprN2CY2ttTS1NAx2","level":3,"time":"2018-05-28T14:06:52+00:00","remoteAddr":"******","user":"user_name","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/theming\/styles?v=0","message":"opendir(\/home\/yunohost.app\/nextcloud\/data\/user_name\/cache): failed to open dir: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#123","userAgent":"******","version":"13.0.1.1"}
{"reqId":"r1lSB9Kl1MiBfPArlelE","level":3,"time":"2018-05-28T14:06:53+00:00","remoteAddr":"******","user":"user_name","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/theming\/js\/theming?v=0","message":"opendir(\/home\/yunohost.app\/nextcloud\/data\/user_name\/cache): failed to open dir: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#123","userAgent":"******","version":"13.0.1.1"}
```

**Comment by KibaFox** [comment] 2018-05-28 14:20
I also want to confirm that I can get Nextcloud working if I uninstall it and reinstall it, but every time I do a fresh install, I get the Internal Server error.

#82 is also probably related.

**Comment by JimboJoe** [comment] 2018-05-28 18:09
Closing that one as it is definitely a duplicate of #98.
Stay tuned on the other one! :wink:

**Closed by JimboJoe** 2018-05-28 18:09 UTC
Labels: bug
