### ISSUE TITLE
Upgrade of Nextcloud doesn't check for appropriate size of /tmp

### ISSUE THREAD

**Issue by 1989gironimo** [YunoHost-Apps/nextcloud_ynh#374] opened 2021-02-14 13:08 UTC
Had to redo the update after issues complaining about /tmp being full, I'd suggest having a test before upgrading to check if /tmp is bigger than 1G.

**Comment by alexAubin** [comment] 2024-06-24 12:40
Closing as duplicate of https://github.com/YunoHost-Apps/nextcloud_ynh/issues/618

**Closed by alexAubin** 2024-06-24 12:40 UTC
