### ISSUE TITLE
Issue with cron.php missing APCu module

### ISSUE THREAD

**Issue by nathanael-h** [YunoHost-Apps/nextcloud_ynh#439] opened 2021-09-10 16:52 UTC
### The bug

I upgrade to the 22.1.1~ynh1 stable version, and I received emails with this error: 
`OC\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
`

### Context

- Hardware: VM in Proxmox VE, on dedicated machine. 
- YunoHost version: 
```
yunohost: 
  repo: stable
  version: 4.2.8.3
yunohost-admin: 
  repo: stable
  version: 4.2.5
moulinette: 
  repo: stable
  version: 4.2.4
ssowat: 
  repo: stable
  version: 4.2.4
```
- I have access to my server: *Through SSH & through the webadmin *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *Mmmh*
  - If yes, please explain: I have this nextcloud instance for many years, maybe 5 or 6, updated with Yunohost, installed some extension needed more stuff (eg: imagemagick ), but not very strange mods...
- Using, or trying to install package version/branch: stable

### Steps to reproduce

SSH, run as root : 
`sudo -u nextcloud /usr/bin/php7.3  -f /var/www/nextcloud/cron.php`
`OC\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)`

For your information here is what I have in nextcloud's cron:
```
~$ sudo crontab -l -u nextcloud
# */15  *  *  *  * nextcloud /usr/bin/php7.3 -f /var/www/nextcloud/cron.php
# */10  *  *  *  * nextcloud /usr/bin/php7.3 /var/www/nextcloud/occ preview:pre-generate

*/15  *  *  *  * /usr/bin/php7.3 -f /var/www/nextcloud/cron.php
# */10  *  *  *  * /usr/bin/php7.3 /var/www/nextcloud/occ preview:pre-generate
```

### Expected behavior

Cron running well :wink: 

It works if I add `--define apc.enable_cli=1` in the command.  I found this in this commit : https://github.com/YunoHost-Apps/nextcloud_ynh/commit/51c5b71f2bec6c3a64b649301513712a87ce1794
It removed extra lines in cron.

### Logs:
https://paste.yunohost.org/raw/qekoyequpu

**Comment by zamentur** [comment] 2021-09-10 17:22
Could you do :
```
cat /etc/cron.d/nextcloud
```
` --define apc.enable_cli=1` seems added in this file since your upgrade (i read your upgrade log).

**Comment by nathanael-h** [comment] 2021-09-10 19:45
Yep : 
```
~$ cat /etc/cron.d/nextcloud
*/15  *  *  *  * nextcloud /usr/bin/php7.3 --define apc.enable_cli=1 -f /var/www/nextcloud/cron.php
```

Should I clean this with crontab -e -u nextcloud :arrow_down:  ?
```
~$ sudo crontab -l -u nextcloud
 */15  *  *  *  * /usr/bin/php7.3 --define apc.enable_cli=1 -f /var/www/nextcloud/cron.php
# */10  *  *  *  * nextcloud /usr/bin/php7.3 /var/www/nextcloud/occ preview:pre-generate
```

For your information: 
```
~$ sudo cat /var/spool/cron/crontabs/nextcloud
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/crontab.Crz5MY/crontab installed on Fri Sep 10 21:38:48 2021)
# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
 */15  *  *  *  * /usr/bin/php7.3 --define apc.enable_cli=1 -f /var/www/nextcloud/cron.php
# */10  *  *  *  * nextcloud /usr/bin/php7.3 /var/www/nextcloud/occ preview:pre-generate
```

**Comment by zamentur** [comment] 2021-09-11 15:26
On other instances i have:
```
$ crontab -l -u nextcloud
no crontab for nextcloud
```
Are you sure you didn't add this cron in crontab yourself ?

**Comment by nathanael-h** [comment] 2021-09-12 15:45
Mmh maybe a long time ago, I do not remember. Thanks I'll remove this crontab and rely on the file in etc/cron.d/nextcloud

11 sept. 2021 17:27:15 ljf (zamentur) ***@***.***>:

**Comment by shukon** [comment] 2021-09-25 12:51
For what it's worth: https://github.com/nextcloud/server/issues/27781

**Comment by tituspijean** [comment] 2023-10-16 09:56
Duplicate of #434

**Closed by tituspijean** 2023-10-16 09:56 UTC
