### ISSUE TITLE
multiple issues with failed upgrade to 18.0.2

### ISSUE THREAD

**Issue by chiajlingvoj** [YunoHost-Apps/nextcloud_ynh#280] opened 2020-03-30 15:53 UTC
System background: I am running yunohost on an armbian base on an odroidhc1.

I already did the upgrade of the core system to 3.7 and then tried to do the nc upgrade to 18.0.2... it failed with the first error occurring in _common.sh at line 645, saying that the command lsb_release doesn't exist... after the failed upgrade, nextcloud was removed from my system, although thankfully I am able to restore from backup.

A second issue, which may or may not belong here, is strange behavior relating to the file extra_php_version.list in /etc/apt/sources.list.d. It consists of the single malformed line:

deb https://packages.sury.org/php/ main https://packages.sury.org/php/  main

Which was preventing me from running additional updates for system files. When I ssh in and manually change it to read:

deb https://packages.sury.org/php/ stretch main

I am able to run system upgrades, etc. but then when I logout and login again the extra_php_version.list file has gone back to what it was before!

**Comment by maniackcrudelis** [comment] 2020-03-30 16:17
Install the package `lsb-release`, it should solve the issue.

**Comment by chiajlingvoj** [comment] 2020-03-30 18:41
I am trying that, but having problems... seems like there is something weird about this particular build of armbian

**Comment by Josue-T** [comment] 2020-03-30 21:28
> I am trying that, but having problems... seems like there is something weird about this particular build of armbian

It's probably a problem which should be fixed in the core as we have many apps which use this command.

**Comment by chiajlingvoj** [comment] 2020-03-31 19:19
the lsb_release issue is working now, I just had to install the package lsb-compat on my version of armbian

**Comment by pintman** [comment] 2020-04-06 13:30
I have problems upgrading yunohost resulting in the following error.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 301, in wrapper
    curr_v = params[k]
KeyError: 'app'
```

The package lsb-release is already installed.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	YunoHost
Description:	YunoHost GNU/Linux 9.12 (stretch)
Release:	9.12
Codename:	stretch
```

**Comment by alexAubin** [comment] 2020-04-06 13:33
@pintman : can you provide the full log since the piece of log you mentioned is only a benign error ?

**Comment by alexAubin** [comment] 2020-04-06 13:40
@Josue-T : 

>It's probably a problem which should be fixed in the core as we have many apps which use this command.

Fixed in https://github.com/YunoHost/yunohost/commit/3bd6a7aa2983f19237939ade661ebee1780461ed

**Comment by pintman** [comment] 2020-04-06 14:33
The complete log is too long for a post but available [here](https://gist.github.com/pintman/34353e5f55142f59c562ae539fb6dd50). @alexAubin

**Comment by alexAubin** [comment] 2020-04-06 14:41
@pintman : yes ;) Github's gist does the trick, but you should have a button "Paste on yunopaste" to automatically paste it on paste.yunohost.org

Anyway, your real issue is about: 

```
2020-04-06 15:21:21,829: DEBUG - ++ wget -nv -O app.tar.bz2 https://download.nextcloud.com/server/releases/nextcloud-16.0.0.tar.bz2
2020-04-06 15:21:21,929: DEBUG - + local 'out=The certificate'\''s owner does not match hostname ‘download.nextcloud.com’'
2020-04-06 15:21:21,930: WARNING - Corrupt source
```

For some reason, your server attempted to download the new files from download.nextcloud.com and a certificate issue got in the way ... Could be due to many thing. Maybe that's just a temporary network issue on your side ... Naively you can try to manually run '`wget -nv -O app.tar.bz2 https://download.nextcloud.com/server/releases/nextcloud-16.0.0.tar.bz2`' on your server and see if that works ...

**Comment by pintman** [comment] 2020-04-06 14:57
I missed the big green yunopaste button. Sorry for that. :-/

Currently I get the same error on the server. I will wait and try later. Thanks for your hint. :)

**Comment by tituspijean** [comment] 2023-10-16 09:35
Closing, as the issue is stale and hopefully solved. Feel free to reopen if needed.

**Closed by tituspijean** 2023-10-16 09:35 UTC
