### ISSUE TITLE
Dav access broken after upgrade

### ISSUE THREAD

**Issue by MCMic** [YunoHost-Apps/nextcloud_ynh#180] opened 2019-03-22 14:45 UTC
Since last upgrade to 15.0.4, dav access from phones is not working.

Access from my computer with the nextcloud client works.

From the phone (Android), Nextcloud app says it has no network access, and DavX says it fails to connect to "<mytld>/127.0.0.1:443". I have no idea why there is 127.0.0.1 in this url.
My nextcloud is at "<mytld>/nextcloud".

Two phones which where syncing fine before the update are now showing this error so I expect it to be on server side.

I checked the config.php of nextcloud and it seems fine, it does not mention 127.0.0.1.

**Comment by JimboJoe** [comment] 2019-03-22 18:46
Not reproducing as I'm using Nextcloud 15.0.4 and DAVx5 myself(2.2.3.1-ose)... Did you try looking into your client configuration? Do your phones have the same client/version?

**Comment by MCMic** [comment] 2019-03-22 19:26
Yes both phones have up to date version from f-droid.

The apps do not give much details about configuration…

But they stopped working right after the update, with the same configuration, so I expect the problem to be on the server side.

I find it really hard to get information, for instance DavX is not explaining where this url comes from. Nextcloud app even pretend I do not have internet…
I did not find any tool to test dav endpoints in a verbose way.

**Comment by MCMic** [comment] 2019-03-24 20:49
Ok, the problem is not with nextcloud I think.

Today it worked from another connection, so I checked and from my phone on my connection, my tld resolves to 127.0.0.1, which is the cause of the other errors.
The DNS server is the same yunohost server so the update must have broke the dns server configuration somehow.

**Comment by JimboJoe** [comment] 2019-07-21 14:59
Given your latest statement that it was not caused by this app, closing for now.

**Closed by JimboJoe** 2019-07-21 14:59 UTC
