### ISSUE TITLE
Nginx rule for Rich Documents / CODE is missing a path for ARM64

### ISSUE THREAD

**Issue by csolisr** [YunoHost-Apps/nextcloud_ynh#376] opened 2021-02-17 14:28 UTC
By default, YunoHost's settings for Nextcloud are only enabling the x64 route for the bundled Collabora Office package, and not the ARM64 one which is used for example on the Raspberry Pi 4. In order to enable access to that version, it's necessary to modify the line in `/etc/nginx/conf.d/{your_nextcloud_path}.d/nextcloud.conf` from this:

```
location ~ ^/(?:index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|oc[ms]-provider\/.+|.+\/richdocumentscode\/proxy)\.php(?:$|\/) {
```

to the following:

```
location ~ ^/(?:index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|oc[ms]-provider\/.+|.+\/richdocumentscode\/proxy|.+\/richdocumentscode_arm64\/proxy)\.php(?:$|\/) {
```

**Comment by fakhryhizballah** [comment] 2022-04-22 04:09
I've used the configuration, but my application is running slow, almost unusable and on the server there is no cpu increase

**Comment by lapineige** [comment] 2023-04-07 16:52
Is this still an issue ?

**Comment by MSmolarz** [comment] 2024-07-01 12:06
Hi, I recently set up YunoHost on my Raspberry Pi 4 and tried the Collabora Online - Built-in CODE Server.
The problem is solved as nextcloud itself has implemented the fix for the ngnix configuration (see: https://github.com/nextcloud/helm/pull/540).

**Comment by alexAubin** [comment] 2024-07-24 16:44
Closing because supposedly fixed by https://github.com/YunoHost-Apps/nextcloud_ynh/commit/115cf2f109a0213bc2a65936ec6dede3325d160e

**Closed by alexAubin** 2024-07-24 16:44 UTC
Labels: onlyoffice / collabora
