### ISSUE TITLE
No SSO when installing at the root of a domain

### ISSUE THREAD

**Issue by djibux** [YunoHost-Apps/nextcloud_ynh#155] opened 2019-01-04 22:42 UTC
Hello,
When installing Nextcloud at the root of a domain, SSO in not working.

Test case:
* fresh install
* Yunohost main domain installed on `portal.example.com`
* Nextcloud installed at the root of `example.com` (or the root of any other domain: `otherdomain.com`, `cloud.example.com`…)
* Log in the portal then access Nextcloud

Result: Nextcloud login form is displayed
Expected result: Nextcloud logs in automatically using portal credentials

I could detect at least one issue: `example.com/ynhpanel.js` returns a 404.  There is probably a conflict between Nextcloud config and yunohost panel config.

I'm happy to help with debugging.  I have tried messing with ssowat config and nginx config without luck so far.

**Comment by JimboJoe** [comment] 2019-01-05 09:46
Hello,
thanks for you report!
Could please try with the latest testing release and report back?
Thanks!

**Comment by djibux** [comment] 2019-01-05 13:58
I have just installed a testing release on a fresh install using
```sudo yunohost app install https://github.com/YunoHost-Apps/nextcloud_ynh/tree/testing --debug```

There is no longer a 404 in the network logs, but ynhpanel.js doesn't seem to be loaded in that version.

Please let me know how I can help.

**Comment by JimboJoe** [comment] 2019-01-05 18:14
OK, thanks... but does the SSO work?

**Comment by djibux** [comment] 2019-01-05 19:12
No :(

Le 5 janvier 2019 19:14:09 GMT+01:00, JimboJoe <notifications@github.com> a écrit :
>OK, thanks... but does the SSO work?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/YunoHost-Apps/nextcloud_ynh/issues/155#issuecomment-451678386

-- 
djib

**Comment by JimboJoe** [comment] 2019-01-06 09:07
OK, I reproduced it in my development environment. I had hard times figuring out why it was still working in my production environment.

The fact is that the SSO seems to only work with Nextcloud if the portal URL is included in Nextcloud URL. In my case, my portal is on mydomain.com, and Nextcloud is on cloud.mydomain.com, and that works. It won't work if Nextcloud is on myseconddomain.com...

I must admit that despite having tried a few times, I've never figured out how SSO worked on Nextcloud (I don't see any specific configuration/code related to that feature in the YunoHost package).
But maybe this restriction is a "feature" of SSOwat...?
cc @Psycojoker @alexAubin @Josue-T

**Comment by djibux** [comment] 2019-01-06 09:45
Thanks for testing.

With the current stable version, SSO works cross domain but only if the app is in a subfolder.
For example : portal on mydomain.com and cloud on myotherdomain.com/nextcloud/.

I will try with the current testing version.

Le 6 janvier 2019 10:08:00 GMT+01:00, JimboJoe <notifications@github.com> a écrit :
>OK, I reproduced it in my development environment. I had hard times
>figuring out why it was still working in my production environment.
>
>The fact is that the SSO seems to only work with Nextcloud if the
>portal URL is included in Nextcloud URL. In my case, my portal is on
>mydomain.com, and Nextcloud is on cloud.mydomain.com, and that works.
>It won't work if Nextcloud is on myseconddomain.com...
>
>I must admit that despite having tried a few times, I've never figured
>out how SSO worked on Nextcloud (I don't see any specific
>configuration/code related to that feature in the YunoHost package).
>But maybe this restriction is a "feature" of SSOwat...?
>cc @Psycojoker @alexAubin @Josue-T 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/YunoHost-Apps/nextcloud_ynh/issues/155#issuecomment-451726585

-- 
djib

**Comment by djibux** [comment] 2019-01-06 11:11
I am sorry I get mixed up.  You are right, it doesn't work cross domain even with the current stable release.

It works for some other apps though, Wordpress being one example.

**Comment by djibux** [comment] 2019-01-12 21:16
Hello,

I have found out that removing `unprotected_uris: /` from `/etc/yunohost/apps/nextcloud/settings.yml` makes the SSO work (but breaks other things such as application passwords).

**Comment by dosch** [comment] 2019-02-19 12:38
same here.

**Comment by alexAubin** [comment] 2020-09-05 12:48
Closing because should be fixed in yunohost 4.0.7

**Comment by djibux** [comment] 2020-09-05 19:22
I have version 4.0.7 and I still experience the issue.  I didn't test with a fresh install.

**Comment by dosch** [comment] 2020-09-17 20:10
same here. No change.

**Comment by kay0u** [comment] 2020-09-18 07:32
When you navigate to https://your.nextcloud.domain.tld/yunohost/sso, you don't have access to the sso?

You should probably regenerate you nginx conf

```
yunohost tools regen-conf nginx -f
```

**Comment by dosch** [comment] 2020-09-18 07:55
It seems like you are not referring to the original issue above...

The problem is not the SSO of YNH.
Please read OP.

**Comment by kay0u** [comment] 2020-09-18 08:52
Yes, indeed, I was troubled by another ~~similar~~ problem. You can follow [here](https://github.com/YunoHost/issues/issues/1270) the issue

**Comment by djibux** [comment] 2020-09-19 14:32
Could this issue be reopened?  It still happens with the latest Yunohost version.

Thanks.

**Closed** 2020-09-19 14:43 UTC

**Comment by alexAubin** [comment] 2020-09-19 14:44
Well we can reopen it, there's already https://github.com/YunoHost/issues/issues/1270 ... so that sounds like a duplicate issue ... Except if you're able to demonstrate that these are two separate ones ... (In fact there's indeed multiple situation to address, and one of them was addressed in 4.0, which is why I closed the issue earlier .. the other one described in #1270 remains to be addressed)

**Comment by djibux** [comment] 2020-09-19 14:53
OK, fair enough.
