### ISSUE TITLE
Nextcloud Hub 8 (29.0.8)

### ISSUE THREAD

**Issue by genma** [YunoHost-Apps/nextcloud_ynh#740] opened 2024-10-25 08:48 UTC
Hi,

I see that Nextcloud 29.0.8 (latest patch for this version) is in testing and waiting to be merged. 
https://github.com/YunoHost-Apps/nextcloud_ynh/pull/735/commits/7a23074a5c2fd386915806052a23a609997f9da9
Do you need some help to release the fix in stable branch ?

**Comment by ericgaspar** [comment] 2024-10-25 08:53
The CI is having trouble validating all tests (probably due to changes in our infrastructure).
In the meantime, you can test Nextcloud 29.0.8 on your server with
`sudo yunohost app upgrade nextcloud -u https://github.com/YunoHost-Apps/nextcloud_ynh/tree/testing --debug` 
(Closing as this is not a bug)

**Closed by ericgaspar** 2024-10-25 08:53 UTC
