### ISSUE TITLE
Download of upload file fails for nextcloud-29.0.9.tar.bz2

### ISSUE THREAD

**Issue by utzer** [YunoHost-Apps/nextcloud_ynh#756] opened 2024-11-27 20:11 UTC
When I wanted to update Nextcloud for Yunohost today I found that nextcloud-29.0.9.tar.bz2 fails to download, a quick check showed that the file is missing in the source [here](https://download.nextcloud.com/server/releases/). You can find the whole log from the failed update [here](https://paste.yunohost.org/raw/omiyusigur). 

And [here](https://help.nextcloud.com/t/november-releases-30-0-2-29-0-9-and-28-0-12/209312/13) you can find the reason, 29.0.9 was pulled, so unpublished.

**Comment by rodinux** [comment] 2024-11-27 20:53
I have the same problem yesterday night. Nextcloud decide to remove this version

https://help.nextcloud.com/t/29-0-9-pulled-from-download-servers/210877

After the upgrade crashed, I have removed the app nextcloud and restore the backup.

**Comment by utzer** [comment] 2024-11-28 05:52
For me the update failed but Nextcloud was still working. Otherwise I would have lost some hours to restore (in worst case).

**Comment by stemy2** [comment] 2024-11-28 10:05
I'm unable to even install nextcloud because of this.

**Comment by ericgaspar** [comment] 2024-11-28 10:42
try the 30.0.2 version 
`sudo yunohost app install https://github.com/YunoHost-Apps/nextcloud_ynh/tree/testing`

**Comment by stemy2** [comment] 2024-11-28 12:11
> try the 30.0.2 version `sudo yunohost app install https://github.com/YunoHost-Apps/nextcloud_ynh/tree/testing`

It fails for the exact same reason.

**Comment by drewwalton19216801** [comment] 2024-11-28 17:12
> try the 30.0.2 version `sudo yunohost app install https://github.com/YunoHost-Apps/nextcloud_ynh/tree/testing`

Does not work. What a broken experience.

**Comment by ericgaspar** [comment] 2024-11-28 19:35
@drewwalton19216801 you should complain to Nextcloud forum about it. The version 29.0.9 has been removed from they repo upstream
cf. https://help.nextcloud.com/t/29-0-9-pulled-from-download-servers/210877

**Comment by stemy2** [comment] 2024-11-28 21:55
Do you mean that the YNH team is totally powerless about this problem and all we have to do is hoping that nextcloud does something about it ?

**Comment by drewwalton19216801** [comment] 2024-11-28 22:09
> @drewwalton19216801 if you want to complain, you should complain to Nextcloud forum about it. The version 29.0.9 has been removed from they repo upstream cf. https://help.nextcloud.com/t/29-0-9-pulled-from-download-servers/210877

Last I checked this is a Yuno-maintained package, therefore their team is responsible for... maintaining it.

**Comment by utzer** [comment] 2024-11-29 05:07
> > @drewwalton19216801 if you want to complain, you should complain to Nextcloud forum about it. The version 29.0.9 has been removed from they repo upstream cf. https://help.nextcloud.com/t/29-0-9-pulled-from-download-servers/210877
> 
> Last I checked this is a Yuno-maintained package, therefore their team is responsible for... maintaining it.

Of course they have to fix it, for me the first fix could be to pull the current update to that version and then release the update to the .10 that will be released next week. 

It is not the fault of the team here. 

My motivation to open the issue here is to let the maintainers here know that they have to do.something. Personally I hope to support them by this, I provided all the easy to find information and now people coming to the project here will know what is going on.

**Comment by ericgaspar** [comment] 2024-11-29 07:07
I made a branch with the version 29.0.8 if that can help
`sudo yunohost app install https://github.com/YunoHost-Apps/nextcloud_ynh/tree/29.0.8`
or if upgrading from a version below 29.0.8
`sudo yunohost app upgrade nextcloud -u https://github.com/YunoHost-Apps/nextcloud_ynh/tree/29.0.8`

I would have honestly liked the tone to be a little more relaxed towards these volunteers who maintain this package... 🙄

**Comment by autra** [comment] 2024-11-29 08:32
> Last I checked this is a Yuno-maintained package, therefore their team is responsible for... maintaining it.

With this kind of reasoning, I can argue than users are responsible for... funding it, then :-) 

> I would have honestly liked the tone to be a little more relaxed towards these volunteers who maintain this package... 🙄

👍🏻 👍🏻 

---

That being sad, @ericgaspar: would it be possible to merge this branch (29.0.8) into testing please, so that the update disappear from `yunohost tools update` and the app is installable again from the gui?

And thanks for all the good work. This hiccup is really not a big deal, as no instances will be lost. From my experience, the nextcloud_ynh is in a much better place now than 2 years ago.

**Comment by souldessin** [comment] 2024-11-30 08:04
I also had the issue and I would like to thank the maintainers for doing the work they do.

These regressions in large projects are bound to happen. At least the good upgrade management prevented anyone losing data.

**Comment by drewwalton19216801** [comment] 2024-12-01 05:12
> With this kind of reasoning, I can argue than users are responsible for... funding it, then :-)

Absolutely correct, which is why I made a donation to the project since I find it useful.

Also, my previous tone was less than desirable, my apologies.

**Comment by utzer** [comment] 2024-12-05 09:05
29.0.10 should be released today, see [here](https://help.nextcloud.com/t/30-0-3-rc2-29-0-10-rc1-and-28-0-13-rc1/211068). 

Thanks for the work on this, highly appreciated!

**Comment by stemy2** [comment] 2024-12-06 10:52
> 29.0.10 should be released today, see [here](https://help.nextcloud.com/t/30-0-3-rc2-29-0-10-rc1-and-28-0-13-rc1/211068).

Since the nexcloud installer/updater is still looking for the 29.0.9 version, it doesn't help us much.

**Comment by ericgaspar** [comment] 2024-12-06 11:05
> Since the nexcloud installer/updater is still looking for the 29.0.9 version, it doesn't help us much.

is it?

this should be fixed.

**Closed by ericgaspar** 2024-12-06 11:05 UTC

**Comment by utzer** [comment] 2024-12-06 11:59
> Since the nexcloud installer/updater is still looking for the 29.0.9 version, it doesn't help us much.

I just wanted to leave the information here, I checked also now, it is released, at least the file is available in the source files. 


> is it?
> 
> this should be fixed.

Not here:
![image](https://github.com/user-attachments/assets/d02c740e-78b3-4300-b7b3-0d002f232dbd)

Anyway, I will start the update tonight or on the weekend.

**Comment by utzer** [comment] 2024-12-06 16:31
Now with 29.0.5 I don't see any updates.

**Comment by ericgaspar** [comment] 2024-12-06 18:22
if this PR is closed it is because there is nothing else to do but wait for the catalog to be updated.

Also, be awar of https://help.nextcloud.com/t/28-0-13-and-30-0-3-withdrawn/211672

**Comment by utzer** [comment] 2024-12-07 06:52
> wait for the catalog to be updated.

Alright, that seems to be the case now. Didn't know it takes that extra step that causes a delay. Will get onto this later this weekend. 

Thanks!

**Comment by Plumeros** [comment] 2024-12-07 09:21
I just installed Nextcloud 29.0.10~ynh1 and it worked like a charm. Ticket is closed from my perspective.

**Comment by utzer** [comment] 2024-12-13 08:18
Here it worked without any problem as well.
