### ISSUE TITLE
Nextcloud send emails about "localhost" instead of my domain name

### ISSUE THREAD

**Issue by Jibec** [YunoHost-Apps/nextcloud_ynh#17] opened 2017-01-21 21:45 UTC
Hi, Nextcloud 10 sends email refering to "localhost" instead of my domain name

> Bonjour Prénom Nom,
> 
> Vous recevez ce message car l'activité suivante a eu lieu sur **_http://localhost/_**
> 
>         marine a partagé Photos avec vous - Aujourd’hui 22:00:01

I didn't have the chance to test it with nextcloud 11 yet since I haven't done the update.
It would be great to fix this! Thanks for your help

**Comment by maniackcrudelis** [comment] 2017-01-21 22:18
Je pense que c'est lié à ça:
https://github.com/nextcloud/server/blob/master/config/config.sample.php#L280

La config embarquée doit dater de très longtemps...

**Comment by polytan02** [comment] 2017-02-16 00:29
On my nextcloud, I set up smtp instead of php_mail() to send emails such as : 
- type : smtp
- starttls
- source : admin @ domain.tld
- auth : login (with auth required)
- server : domain.tld
- port : 587
- login : theadminuser
- passwd : theadminpassword.

I'm sure all of this can be automated ?

**Comment by Bugsbane** [comment] 2017-02-18 12:48
Isn't this just a seeing in the Nextcloud config.php file? I know that originally, my Nextcloud 10 install was sending emails from localhost until I changed a seeing from localhost to my domain name. Not sure if we're talking about the same thing though.

**Comment by polytan02** [comment] 2017-02-18 13:02
@Jibec have you try to setup your nextcloud to smtp as per my details above to see of the problem is still there ?

**Comment by polytan02** [comment] 2017-02-21 23:37
The interest of using smtp@587 versus php_mail() is that the emails sent with smtp are actually signed by dkim. This means there are less chance of the email (such as sending a link to share files, etc) to be noticed as spam by the receiver.

I can do it "manually" but I don't know how to automate this setup at install/upgrade

**Comment by JimboJoe** [comment] 2019-07-21 14:54
Fixed by https://github.com/YunoHost-Apps/nextcloud_ynh/pull/175

**Closed by JimboJoe** 2019-07-21 14:54 UTC
Labels: bug
